project:
  type: book
  
lang: de

book:
  title: "Bachelorseminar"
  author: "Sebastian Sauer"
  date: today
  repo-url: https://bachelorseminar.netlify.app/
  chapters:
    - index.qmd
    - 005-hinweise.qmd
    - 010-pruefung.qmd
    - 020-hinweise-thesis.qmd
    - 030-reviews.qmd
    - 050-ressourcen.qmd
    - 100-Literatur.qmd
    


bibliography: bib/bib.bib
format:
  html:
    toc: true
    theme:
      light: sandstone
      dark: solar
    #css: styles.css
    number-sections: true
    df-print: paged
    code-fold: false
    fig-align: center
    code-link: true
    mermaid:
      theme: neutral



